language: java
sudo: true
jdk: oraclejdk8
before_install:
  - chmod +x mvnw
services:
  - mysql
#  Check this url for explanation
#  https://sivalabs.in/2018/01/ci-cd-springboot-applications-using-travis-ci/
script: mvn clean test -Dtest="com.travelagency.unittest.Test*"